---
title: "SACADA project - Interactive visualisation"
author: "Ngoc-Du M Luong"
date: "16/12/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load("2022_01_06_100Workers_56days_Step5_Schedule_Location_Mask_StatusCounter_SIRday0.RData")
load("DATA_CheckPoint1.RData")
```

```{r packages, include=FALSE}
##### PACKAGES #####
library(ggplot2)
library(reshape2)
library(plotly)
library(stringr)
library(data.table)
library(dplyr)
```

<style> div.main-container { max-width: 1200px; } </style>


## Schedule

```{r plant, echo=FALSE}
inputPanel(
  # selectInput("n_breaks", label = "Number of bins:",
  #             choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("Day_sldr", label = "Day",
              min = 1, max = 56, value = 1, step = 1),
  sliderInput("Hour_sldr", label = "Hour",
              min = 0, max = 23, value = 0, step = 1),
  sliderInput("Min_sldr", label = "Minute",
               min = 0, max = 55, value = 0, step = 5) 
)

renderPlot({
  # hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
  #      xlab = "Duration (minutes)", main = "Geyser eruption duration")
  # 
  # dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  # lines(dens, col = "blue")
  t_ind <- f_convertTime("time2ind",dt = 5,
                         D=input$Day_sldr, H=input$Hour_sldr, M=input$Min_sldr)
  f_plotWorkers(g_emptyPlant, MyWorkers, ti = t_ind)
},
  width=1100, heigh=850)
```

