---
title: "A reference scenario"
---

# Computing

## Input data - Reference scenario

In view of the all parameters described above, based on literature data, expert knowledge and investigations, a set of the most likely parameter values was set to define a reference scenario. These parameter values, set by default as input of all model computations, constitutes then references for further comparative analyses such as simulation convergence check, parameter sensitivity analyses or scenario simulations. All default values are provided in attached spreadsheet (*parameters_reference_xlsx*). This reference scenario was characterized by computing the virus transmission between workers, surfaces and meat portions in a processing plant from one initial infected worker during 42 days with five-minute time steps.

## Output indicators

In this project, output indicators are multiple depending on the aim the study. These indicators can be directly obtained or estimated from the simulations in order to describe the infection of the workers, the contamination of the surfaces and the food products processed in the plant. One can cite, for example to describe the infection of the workers, the probability to have a cluster of at least 25 infection cases (based on criteria by the French national public health agency) as well as its uncertainty range, the number of infected workers at the peak of the epidemiological curve, the number of days before reaching this peak, the initial or effective transmission rate $R_0$ or $R_t$, etc. Considering the food contamination, one can estimate for example the average daily ratio of contaminated food portions over a several-day period with a detection of viral RNA copies reaching a predefined threshold level (e.g. 4log, 5log, etc.). Finally, for the surfaces contamination, one can estimate the frequency of the different surfaces daily exceeding a threshold viral RNA copies level and possibly carry out comparisons between the different locations in the plant.